[package]
name = "multi-tasker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] } 
chrono = "0.4.2"
daemonize = "0.5.0"
tokio = { version = "1.36.0", features = ["full"] }
