[package]
name = "multi-tasker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] } 
chrono = "0.4.2"
daemonize = "0.5.0"
tokio = { version = "1.36.0", features = ["full"] }
serde = { version = "1.0.196", features = ["derive"] }
home = "0.5.9"
whoami = "1.4.1"
procfs = "0.16.0"
bincode = "1.3.3"
glob = "0.3.1"
sysinfo = "0.30.5"
ascii_table = "4.0.3"
colored = "2.1.0"
prettytable = "0.10.0"
notify = "6.1.1"
rev_lines = "0.3.0"
env_logger = "0.11.2"
