[package]
name = "mult_spawn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mult_lib = { path = "../mult_lib" }
home = "0.5.9"
